CREATE TABLE dbo.Skills
	(
	Id int NOT NULL IDENTITY (1, 1),
	Name nvarchar(100) NOT NULL,
	Description nvarchar(MAX) NULL
	)  ON [PRIMARY]
	 TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE dbo.Skills ADD CONSTRAINT
	PK_Skills PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.Skills SET (LOCK_ESCALATION = TABLE)
GO
