CREATE TABLE dbo.Tokens
	(
	Id int NOT NULL IDENTITY (1, 1),
	TokenGuid uniqueidentifier NOT NULL,
	UserId int NOT NULL,
	CreatedAt datetime NOT NULL,
	LastRequestAt datetime NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Tokens ADD CONSTRAINT
	PK_Token_Id PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
CREATE UNIQUE NONCLUSTERED INDEX IX_Token ON dbo.Tokens
	(
	TokenGuid
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE dbo.Tokens ADD CONSTRAINT
	FK_Tokens_Users FOREIGN KEY
	(
	UserId
	) REFERENCES dbo.Users
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.Tokens SET (LOCK_ESCALATION = TABLE)
GO
