BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.Patrols
	(
	Id int NOT NULL IDENTITY (1, 1),
	Name [varchar](256) NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Patrols ADD CONSTRAINT
	PK_Patrols_Id PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE TABLE dbo.Plans
	(
	Id int NOT NULL IDENTITY (1, 1),
	PatrolId int NOT NULL,
	Name [varchar](256) NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Plans ADD CONSTRAINT
	PK_Plans_Id PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE dbo.Plans ADD CONSTRAINT
	FK_Plans_Users FOREIGN KEY
	(
	PatrolId
	) REFERENCES dbo.Patrols
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
GO
CREATE TABLE dbo.PatrolUsers
	(
	Id int NOT NULL IDENTITY (1, 1),
	PatrolId int NOT NULL,
	UserId int NOT NULL,
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.PatrolUsers ADD CONSTRAINT
	PK_PatrolUsers_Id PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE dbo.PatrolUsers ADD CONSTRAINT
	FK_PatrolUsers_Users FOREIGN KEY
	(
	UserId
	) REFERENCES dbo.Users
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
GO
ALTER TABLE dbo.PatrolUsers ADD CONSTRAINT
	FK_PatrolUsers_Patrols FOREIGN KEY
	(
	PatrolId
	) REFERENCES dbo.Patrols
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
GO
ALTER TABLE dbo.Plans SET (LOCK_ESCALATION = TABLE)
GO
ALTER TABLE dbo.Patrols SET (LOCK_ESCALATION = TABLE)
GO
ALTER TABLE dbo.PatrolUsers SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
