
CREATE TABLE dbo.Patrols
	(
	Id int NOT NULL IDENTITY (1, 1),
	Name varchar(256) NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Patrols ADD CONSTRAINT
	PK_Patrols PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.Patrols SET (LOCK_ESCALATION = TABLE)
GO
CREATE TABLE dbo.Sections
	(
	Id int NOT NULL IDENTITY (1, 1),
	Name varchar(256) NOT NULL,
	PatrolId int NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Sections ADD CONSTRAINT
	PK_Sections PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.Sections ADD CONSTRAINT
	FK_Sections_Patrols FOREIGN KEY
	(
	PatrolId
	) REFERENCES dbo.Patrols
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.Sections SET (LOCK_ESCALATION = TABLE)
GO
CREATE TABLE dbo.Plans
	(
	Id int NOT NULL IDENTITY (1, 1),
	Name varchar(256) NOT NULL,
	PatrolId int NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Plans ADD CONSTRAINT
	PK_Plans PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.Plans ADD CONSTRAINT
	FK_Plans_Patrols FOREIGN KEY
	(
	PatrolId
	) REFERENCES dbo.Patrols
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.Plans SET (LOCK_ESCALATION = TABLE)
GO
CREATE TABLE dbo.PlanSections
	(
	Id int NOT NULL IDENTITY (1, 1),
	PlanId int NOT NULL,
	SectionId int NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.PlanSections ADD CONSTRAINT
	PK_PlanSections PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.PlanSections ADD CONSTRAINT
	FK_PlanSections_Plans FOREIGN KEY
	(
	PlanId
	) REFERENCES dbo.Plans
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.PlanSections ADD CONSTRAINT
	FK_PlanSections_Sections FOREIGN KEY
	(
	SectionId
	) REFERENCES dbo.Sections
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
	
GO
ALTER TABLE dbo.PlanSections SET (LOCK_ESCALATION = TABLE)
GO
CREATE TABLE dbo.Levels
	(
	Id int NOT NULL IDENTITY (1, 1),
	Name varchar(256) NOT NULL,
	Description varchar(256) NULL,
	PatrolId int NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Levels ADD CONSTRAINT
	PK_Levels PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.Levels ADD CONSTRAINT
	FK_Levels_Patrols FOREIGN KEY
	(
	PatrolId
	) REFERENCES dbo.Patrols
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.Levels SET (LOCK_ESCALATION = TABLE)
GO
CREATE TABLE dbo.SectionLevels
	(
	Id int NOT NULL IDENTITY (1, 1),
	SectionId int NOT NULL,
	LevelId int NOT NULL,
	[Order] int NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.SectionLevels ADD CONSTRAINT
	PK_SectionLevels PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.SectionLevels ADD CONSTRAINT
	FK_SectionLevel_Sections FOREIGN KEY
	(
	SectionId
	) REFERENCES dbo.Sections
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.SectionLevels ADD CONSTRAINT
	FK_SectionLevel_Levels FOREIGN KEY
	(
	LevelId
	) REFERENCES dbo.Levels
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.SectionLevels SET (LOCK_ESCALATION = TABLE)
GO
ALTER TABLE dbo.Skills SET (LOCK_ESCALATION = TABLE)
GO
CREATE TABLE dbo.SectionSkills
	(
	Id int NOT NULL IDENTITY (1, 1),
	SectionId int NOT NULL,
	SkillId int NOT NULL,
	[Order] int NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.SectionSkills ADD CONSTRAINT
	PK_SectionSkills PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.SectionSkills ADD CONSTRAINT
	FK_SectionSkills_Skills FOREIGN KEY
	(
	SkillId
	) REFERENCES dbo.Skills
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.SectionSkills ADD CONSTRAINT
	FK_SectionSkills_Sections FOREIGN KEY
	(
	SectionId
	) REFERENCES dbo.Sections
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.SectionSkills SET (LOCK_ESCALATION = TABLE)
GO
ALTER TABLE Skills
ADD PatrolId int not null;
GO
ALTER TABLE dbo.Skills ADD CONSTRAINT
	FK_Skills_Patrols FOREIGN KEY
	(
	PatrolId
	) REFERENCES dbo.Patrols
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
GO