CREATE TABLE dbo.Groups
	(
	Id int NOT NULL IDENTITY (1, 1),
	Name varchar(256) NOT NULL,
	PatrolId int NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Groups ADD CONSTRAINT
	PK_Groups PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.Groups ADD CONSTRAINT
	FK_Plans_Patrols FOREIGN KEY
	(
	PatrolId
	) REFERENCES dbo.Patrols
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO

CREATE TABLE dbo.GroupUsers
	(
	Id int NOT NULL IDENTITY (1, 1),
	GroupId int NOT NULL,
	UserId int NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.GroupUsers ADD CONSTRAINT
	PK_GroupUsers PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.GroupUsers ADD CONSTRAINT
	FK_GroupUsers_Groups FOREIGN KEY
	(
	GroupId
	) REFERENCES dbo.Groups
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.GroupUsers ADD CONSTRAINT
	FK_GroupUsers_Users FOREIGN KEY
	(
	UserId
	) REFERENCES dbo.Users
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO

CREATE TABLE dbo.SectionGroups
	(
	Id int NOT NULL IDENTITY (1, 1),
	GroupId int NOT NULL,
	SectionId int NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.SectionGroups ADD CONSTRAINT
	PK_SectionGroups PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.SectionGroups ADD CONSTRAINT
	FK_SectionGroups_Groups FOREIGN KEY
	(
	GroupId
	) REFERENCES dbo.Groups
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.SectionGroups ADD CONSTRAINT
	FK_SectionGroups_Sections FOREIGN KEY
	(
	SectionId
	) REFERENCES dbo.Sections
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO