name: Test Branch

on:
  push:
    branches-ignore: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      #sql server for db integration tests
      mssql:
        image: mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
        env:
          SA_PASSWORD: ${{ secrets.BROOK_PAT }}comPLEXity!!
          ACCEPT_EULA: Y
          MSSQL_PID: Express
        ports:
          - 1433:1433
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup .NET Core # Required to execute ReportGenerator
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.401
      - name: run tests
        run: dotnet test ./src --verbosity normal
        env:
          ASPNETCORE_ENVIRONMENT: ci
          Test__ConnectionString: 'Server=localhost;User ID=sa;Password=${{ secrets.BROOK_PAT }}comPLEXity!!;'
          
      