name: Build Container, Push to Github, Trigger Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: run tests
        run: dotnet test ./src --verbosity normal
        #--filter TestCategory!=persistence
        
  build_frontend:
    needs: [test]    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    
    #new docker build, to replace the above
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    # TODO: this shouldn't be necassary it seems like
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: brookpatten
        password: ${{ secrets.BROOK_PAT }}
          
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./src/Amphibian.Patrol.Training.Web
        file: ./src/Amphibian.Patrol.Training.Web/Dockerfile
        push: true
        tags: |
          ghcr.io/brookpatten/patrol-training-frontend:ci
          ghcr.io/brookpatten/patrol-training-frontend:dev
          ghcr.io/brookpatten/patrol-training-frontend:build-${{ github.run_number }}
          ghcr.io/brookpatten/patrol-training-frontend:v1.0.${{ github.run_number }}
        
  build_api:
    needs: [test]    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    
    #new docker build, to replace the above
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    # TODO: this shouldn't be necassary it seems like
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: brookpatten
        password: ${{ secrets.BROOK_PAT }}
          
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./src
        file: ./src/Amphibian.Patrol.Training.Api/Dockerfile
        push: true
        tags: |
          ghcr.io/brookpatten/patrol-training-api:ci
          ghcr.io/brookpatten/patrol-training-api:dev
          ghcr.io/brookpatten/patrol-training-api:build-${{ github.run_number }}
          ghcr.io/brookpatten/patrol-training-api:v1.0.${{ github.run_number }}
          
  build_onestop:
    needs: [test]    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
        
    #new docker build, to replace the above
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    # TODO: this shouldn't be necassary it seems like
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: brookpatten
        password: ${{ secrets.BROOK_PAT }}
          
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: |
          ghcr.io/brookpatten/patrol-training-onestop:ci
          ghcr.io/brookpatten/patrol-training-onestop:dev
          ghcr.io/brookpatten/patrol-training-onestop:build-${{ github.run_number }}
          ghcr.io/brookpatten/patrol-training-onestop:v1.0.${{ github.run_number }}
        
  azure-dev-update:
    needs: [build_onestop]
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Dev Update
      uses: joelwmale/webhook-action@master
      with:
        url: ${{ secrets.DEV_WEBHOOK }}