name: Build Docker images and push to Azure Container Registry

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Build frontend
      uses: docker/build-push-action@v1
      with:
        username: patroltraining
        password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
        repository: patroltraining.azurecr.io/frontend
        tags: latest
        dockerfile: src/Amphibian.Patrol.Training.Web/Dockerfile
    - name: Build Api
      uses: docker/build-push-action@v1
      with:
        username: patroltraining
        password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
        repository: patroltraining.azurecr.io/api
        tags: latest
        dockerfile: src/Dockerfile