name: Build Docker images and push to Azure Container Registry

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Build frontend
      uses: docker/build-push-action@v1
      with:
        username: patroltraining
        password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
        registry: patroltraining.azurecr.io
        repository: frontend
        tags: latest
        path: ./src/Amphibian.Patrol.Training.Web
  build_api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Build with dotnet
      run: dotnet publish src/Amphibian.Patrol.Training.sln --runtime=linux-x64
    - name: Build Api
      uses: docker/build-push-action@v1
      with:
        username: patroltraining
        password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
        registry: patroltraining.azurecr.io
        repository: api
        tags: latest
        path: ./src/Amphibian.Patrol.Training.Api
  build_onestop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Build Onestop
      uses: docker/build-push-action@v1
      with:
        username: patroltraining
        password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
        registry: patroltraining.azurecr.io
        repository: onestop
        tags: latest
        path: ./src