name: Build Docker images and push to Azure Container Registry

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Build frontend
      uses: docker/build-push-action@v1
      with:
        username: brookpatten
        password: ${{ secrets.BROOK_PAT }}
        registry: docker.pkg.github.com
        repository: brookpatten/patrol.training/frontend
        tags: latest
        path: ./src/Amphibian.Patrol.Training.Web
  build_api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Build with dotnet
      run: dotnet publish src/Amphibian.Patrol.Training.sln --runtime=linux-x64
    - name: Build frontend
      uses: docker/build-push-action@v1
      with:
        username: brookpatten
        password: ${{ secrets.BROOK_PAT }}
        registry: docker.pkg.github.com
        repository: brookpatten/patrol.training/api
        tags: latest
        path: ./src/Amphibian.Patrol.Training.Api
  build_onestop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Build Onestop
      uses: docker/build-push-action@v1
      with:
        username: brookpatten
        password: ${{ secrets.BROOK_PAT }}
        registry: docker.pkg.github.com
        repository: brookpatten/patrol.training/onestop
        tags: latest
        path: ./src
        
  azure-dev-update:
  
    needs: [build_onestop]
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Dev Update
      uses: joelwmale/webhook-action@master
      with:
        url: ${{ secrets.DEV_WEBHOOK }}