name: Build Container, Push to Github, Trigger Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      #sql server for db integration tests
      mssql:
        image: mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
        env:
          SA_PASSWORD: ${{ secrets.BROOK_PAT }}comPLEXity!!
          ACCEPT_EULA: Y
          MSSQL_PID: Express
        ports:
          - 1433:1433
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup .NET Core # Required to execute ReportGenerator
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.401
      - name: run tests
        run: dotnet test ./src --verbosity normal --collect:"XPlat Code Coverage"
        env:
          ASPNETCORE_ENVIRONMENT: ci
          Test__ConnectionString: 'Server=localhost;User ID=sa;Password=${{ secrets.BROOK_PAT }}comPLEXity!!;'
          
      - name: move coverage file
        run: cp ./src/Amphibian.Patrol.Training.Tests/TestResults/*/coverage.cobertura.xml ./coverage.xml
      
      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@4.7.1
        with:
          reports: './coverage.xml'
          targetdir: './test-coverage-report'
          reporttypes: 'HtmlInline'
          
      - uses: actions/upload-artifact@v2
        with:
          name: test-coverage-report
          path: ./test-coverage-report
        
  build_frontend:
    needs: [test]    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    
    #new docker build, to replace the above
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    # TODO: this shouldn't be necassary it seems like
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: brookpatten
        password: ${{ secrets.BROOK_PAT }}
          
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./src/Amphibian.Patrol.Training.Web
        file: ./src/Amphibian.Patrol.Training.Web/Dockerfile
        push: true
        tags: |
          ghcr.io/brookpatten/patrol-training-frontend:ci
          ghcr.io/brookpatten/patrol-training-frontend:dev
          ghcr.io/brookpatten/patrol-training-frontend:build-${{ github.run_number }}
        
  build_api:
    needs: [test]    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    
    #new docker build, to replace the above
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    # TODO: this shouldn't be necassary it seems like
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: brookpatten
        password: ${{ secrets.BROOK_PAT }}
          
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./src
        file: ./src/Amphibian.Patrol.Training.Api/Dockerfile
        push: true
        tags: |
          ghcr.io/brookpatten/patrol-training-api:ci
          ghcr.io/brookpatten/patrol-training-api:dev
          ghcr.io/brookpatten/patrol-training-api:build-${{ github.run_number }}
          
  build_onestop:
    needs: [test]    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
        
    #new docker build, to replace the above
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    # TODO: this shouldn't be necassary it seems like
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: brookpatten
        password: ${{ secrets.BROOK_PAT }}
          
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: |
          ghcr.io/brookpatten/patrol-training-onestop:ci
          ghcr.io/brookpatten/patrol-training-onestop:dev
          ghcr.io/brookpatten/patrol-training-onestop:build-${{ github.run_number }}
        
  azure-dev-update:
    needs: [build_onestop]
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Dev Update
      uses: joelwmale/webhook-action@master
      with:
        url: ${{ secrets.DEV_WEBHOOK }}
        
    #- name: Login to Azure
    #  uses: Azure/login@v1
    #  with:
    #    creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    #- name: Deploy Dev Api
    #  uses: Azure/webapps-deploy@v2
    #  with:
    #    app-name: webapp-pass-depot-dev
    #    images: ghcr.io/brookpatten/patrol-training-onestop:build-${{ github.run_number }}