name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      run: dotnet build src/schedule.sln --configuration Release
    - name: Run Tests
      run: dotnet test src/schedule.sln
    - name: Create Nuget Package
      run: dotnet pack src/Schedule.Api/Schedule.Api.csproj
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with: 
        name: Nuget Package
        path: src/Schedule.Api/bin/Debug/
    - name: Upload package
      run: dotnet nuget push src/Schedule.Api/bin/Debug/TrainingOrganizer.Api.0.0.1.nupkg --source github
      
