name: Integration Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
        env:
          SA_PASSWORD: ${{ secrets.BROOK_PAT }}comPLEXity!!
          ACCEPT_EULA: Y
          MSSQL_PID: Express
        ports:
          - 1433:1433
        # Set health checks to wait until db has started
        options: >-
          --health-start-period 40s
          --health-cmd "netstat -an | grep 1433 > /dev/null; if [ 0 != $? ]; then exit 1; fi;"
          --health-interval 10s
          --health-timeout 10s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: run tests
        run: dotnet test ./src --verbosity normal --filter TestCategory=persistence
        env:
          ASPNETCORE_ENVIRONMENT: ci
          Test__ConnectionString: 'Server=localhost;User ID=sa;Password=${{ secrets.BROOK_PAT }}comPLEXity!!;'